const RESPONSE_SCHEMA = {
  type: 'OBJECT',
  properties: {
    documentType: { type: 'STRING' },
    title: { type: 'STRING' },
    recipient: { type: 'STRING' },
    subject: { type: 'STRING' },
    content: { type: 'STRING' },
    disclaimer: { type: 'STRING' },
  },
  required: ['documentType', 'title', 'recipient', 'subject', 'content', 'disclaimer'],
};

const normalizeDraftResult = (input, parsed) => {
  const ensureString = (v, fallback = '') => (typeof v === 'string' ? v : fallback);

  return {
    documentType: ensureString(parsed?.documentType, input.documentType || ''),
    title: ensureString(parsed?.title, ''),
    recipient: ensureString(parsed?.recipient, input.recipient || ''),
    subject: ensureString(parsed?.subject, ''),
    content: ensureString(parsed?.content, ''),
    disclaimer:
      ensureString(parsed?.disclaimer, '') ||
      'This document was generated by an AI assistant. Please review, verify, and edit before submission.',
  };
};

const generateDraft = async ({ documentType, recipient, problem, additionalDetails, language = 'en' }) => {
  const apiKey = process.env.GEMINI_API_KEY;

  if (!apiKey || !apiKey.trim()) {
    throw new Error('GEMINI_API_KEY is missing. Please configure the environment variable on the server.');
  }

  try {
    const { generateWithRetry } = require('./geminiHelper')

    const languageInstruction =
      language === 'hi'
        ? 'Generate all user-facing explanatory content in Hindi using clear, natural Devanagari Hindi that is easy for ordinary citizens to understand.'
        : 'Generate all user-facing explanatory content in English.'

    const prompt = `You are the CivicAI Draft Generator. ${languageInstruction} Generate a civic/legal draft following the user input and the rules below.\n\nInstructions and constraints:\n- Use only information provided by the user. Do NOT invent dates, names, amounts, addresses, case numbers, legal sections, government offices, or facts.\n- If information is missing, use clear placeholders such as [Your Name], [Your Address], [Date], [Reference Number, if applicable].\n- Do not pretend to be a lawyer or give legal guarantees. Keep language professional and understandable. Use Indian context where appropriate.\n- For RTI Application use a formal information-request structure but do not invent the name of a Public Information Officer or department.\n- The output must be a JSON object matching the response schema and nothing else. Do not wrap the JSON in markdown fences.\n\nUser input:\ndocumentType: ${documentType}\nrecipient: ${recipient}\nproblem: ${problem}\nadditionalDetails: ${additionalDetails || ''}\n\nProduce a structured JSON with the following keys: documentType, title, recipient, subject, content, disclaimer.\nBe concise but produce a ready-to-edit document. Include placeholders where user info is missing.`;

    const response = await generateWithRetry({
      apiKey,
      model: 'gemini-3.5-flash-lite',
      contents: prompt,
      config: {
        responseMimeType: 'application/json',
        responseSchema: RESPONSE_SCHEMA,
      },
    })

    const rawText = typeof response?.text === 'string' ? response.text.trim() : '';

    if (!rawText) {
      throw new Error('Gemini returned an empty response.');
    }

    let parsed;
    try {
      parsed = JSON.parse(rawText);
    } catch (err) {
      const cleaned = rawText.replace(/^```json\s*/i, '').replace(/```$/i, '').trim();
      parsed = JSON.parse(cleaned);
    }

    return normalizeDraftResult({ documentType, recipient }, parsed);
  } catch (error) {
    if (error && error.code) {
      const e = new Error('Draft generation failed')
      e.code = error.code
      throw e
    }

    const message = error && error.message ? error.message : 'Gemini AI request failed.'
    const e = new Error(`Draft generation failed: ${message}`)
    e.code = 'AI_SERVICE_ERROR'
    throw e
  }
};

module.exports = {
  generateDraft,
};
